---
swagger: '2.0'
info:
  title: os-aggregates
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/os-aggregates":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    get:
      operationId: list_aggregates
      summary: List aggregates
      description: |
        Lists all aggregates.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "aggregates": [
                      {
                          "name": "name",
                          "availability_zone": "nova",
                          "deleted": false,
                          "created_at": "2012-11-16T06:22:23.361359",
                          "updated_at": null,
                          "hosts": [],
                          "deleted_at": null,
                          "id": 1,
                          "metadata": {
                              "availability_zone": "nova"
                          }
                      }
                  ]
              }
    post:
      operationId: create_aggregate
      summary: Create aggregate
      description: |
        Creates an aggregate.
      produces: []
      responses:
        '200':
          description: 200 response
  "/v2/{tenant_id}/os-aggregates/{aggregate_id}":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: aggregate_id
      required: true
      in: path
      type: string
      description: |
        The ID associated with an aggregate.
    delete:
      operationId: delete_aggregate
      summary: Delete aggregate
      description: |
        Deletes an aggregate.
      produces: []
      responses:
        '200':
          description: 200 response
    get:
      operationId: get_details
      summary: Get aggregate details
      description: |
        Gets details about a specified aggregate.
      produces: []
      responses:
        '200':
          description: 200 response
    put:
      operationId: update_aggregate
      summary: Update aggregate
      description: |
        Updates the name, and optionally the availability zone, for a specified aggregate.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "aggregate": {
                      "name": "newname",
                      "availability_zone": "nova2",
                      "deleted": false,
                      "created_at": "2012-12-04T12:04:27.075065",
                      "updated_at": "2012-12-04T12:04:27.242597",
                      "hosts": [],
                      "deleted_at": null,
                      "id": 1,
                      "metadata": {
                          "availability_zone": "nova2"
                      }
                  }
              }
  "/v2/{tenant_id}/os-aggregates/{aggregate_id}/action":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: aggregate_id
      required: true
      in: path
      type: string
      description: |
        The ID associated with an aggregate.
    post:
      operationId: remove_host
      summary: Remove host from aggregate
      description: |
        Removes a host from an aggregate.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "aggregate": {
                      "name": "name",
                      "availability_zone": "nova",
                      "deleted": false,
                      "created_at": "2012-12-04T12:04:26.557909",
                      "updated_at": null,
                      "hosts": [],
                      "deleted_at": null,
                      "id": 1,
                      "metadata": {
                          "availability_zone": "nova"
                      }
                  }
              }